import requests
import time

prompt = "Explain the concept of recursion in programming. in 200 words"

# Function to send a request to the model and get an output
def get_model_output(prompt, model="phi"):
    """
    Args:
        prompt (str): The prompt to send to the model.
        model (str, optional): Name of the model to generate output. Defaults to "phi".

    Returns:
        output (str): The output generated by the model.
        elapsed_time (float): Time taken to get the output in seconds, upto 3 decimal places.
    """
    
    url = "http://localhost:11434/api/generate"
    
    start = time.time()
    
    # Sending a POST request to the model API
    response = requests.post(
        url=url,
        json = {
            "model": model,
            "prompt": prompt,
            "stream": False
        }
    )
    
    end = time.time()
    
    return response.json()['response'], round((end - start), 3)


if __name__ == "__main__":
    prompt = "What are Black Holes? How are they different from Neutron Stars? Explain in detail to a 6 years old child."
    output, time_taken = get_model_output(prompt)
    print("Model Used: phi")
    print(f"Prompt: {prompt}")
    print(f"Output: {output}")
    print(f"Time taken: {time_taken} seconds")